<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-10T21:43:36 IST" name="Default suite" finished-at="2022-07-10T21:43:43 IST" duration-ms="6652">
    <groups>
    </groups>
    <test started-at="2022-07-10T21:43:36 IST" name="Default test" finished-at="2022-07-10T21:43:43 IST" duration-ms="6652">
      <class name="com.restassuredapitesting.testCases.TC008_DDT_AddNewEmployees">
        <test-method signature="PostNewEmployees(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.restassuredapitesting.testCases.TC008_DDT_AddNewEmployees@3f6b0be5]" started-at="2022-07-10T21:43:37 IST" name="PostNewEmployees" data-provider="empdataprovider" finished-at="2022-07-10T21:43:40 IST" duration-ms="2762" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sandy2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[101]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[21]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PostNewEmployees -->
        <test-method signature="PostNewEmployees(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.restassuredapitesting.testCases.TC008_DDT_AddNewEmployees@3f6b0be5]" started-at="2022-07-10T21:43:40 IST" name="PostNewEmployees" data-provider="empdataprovider" finished-at="2022-07-10T21:43:41 IST" duration-ms="984" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sandy5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[104]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[24]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at com.restassuredapitesting.testCases.TC008_DDT_AddNewEmployees.PostNewEmployees(TC008_DDT_AddNewEmployees.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PostNewEmployees -->
        <test-method signature="PostNewEmployees(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.restassuredapitesting.testCases.TC008_DDT_AddNewEmployees@3f6b0be5]" started-at="2022-07-10T21:43:41 IST" name="PostNewEmployees" data-provider="empdataprovider" finished-at="2022-07-10T21:43:42 IST" duration-ms="905" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sandy6]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[105]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PostNewEmployees -->
        <test-method signature="PostNewEmployees(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.restassuredapitesting.testCases.TC008_DDT_AddNewEmployees@3f6b0be5]" started-at="2022-07-10T21:43:42 IST" name="PostNewEmployees" data-provider="empdataprovider" finished-at="2022-07-10T21:43:43 IST" duration-ms="962" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sandy7]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[106]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[26]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:976)
at org.testng.Assert.assertEquals(Assert.java:1010)
at com.restassuredapitesting.testCases.TC008_DDT_AddNewEmployees.PostNewEmployees(TC008_DDT_AddNewEmployees.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PostNewEmployees -->
      </class> <!-- com.restassuredapitesting.testCases.TC008_DDT_AddNewEmployees -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
